sudo: required
language: node_js
node_js:
  - '9'
  - '10'
cache:
  yarn: true
before_install:
  - yarn global add greenkeeper-lockfile@1
before_script:
  - greenkeeper-lockfile-update
after_script:
  - greenkeeper-lockfile-upload
notifications:
  email:
    on_success: never
    on_failure: always
