sudo: false
language: node_js
node_js:
  - '9'
cache:
  yarn: true
services:
  - docker
before_install:
  - npm install -g greenkeeper-lockfile@1
before_script:
  - greenkeeper-lockfile-update
after_script:
  - greenkeeper-lockfile-upload
notifications:
  email:
    on_success: never
    on_failure: always
