sudo: required
language: node_js
node_js:
  - '9'
  - '10'
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn test
before_install:
  - yarn global add greenkeeper-lockfile@1
before_script:
  - greenkeeper-lockfile-update
after_script:
  - greenkeeper-lockfile-upload
before_deploy:
  - npm install now --no-save
deploy:
  - provider: script
    script: now --token $NOW_TOKEN && now alias --token $NOW_TOKEN
    skip_cleanup: true
    on:
      tags: true
      all_branches: true
      condition: $TRAVIS_TAG =~ ^v[0-9]+\.[0-9]+\.[0-9]+
  - provider: script
    script: now --token $NOW_TOKEN && now alias canary.mcansh.blog
    skip_cleanup: true
    on:
      tags: true
      all_branches: true
      condition: $TRAVIS_TAG =~ ^canary.*$
notifications:
  email:
    on_success: never
    on_failure: always
