sudo: required
language: node_js
node_js:
  - '10'
cache:
  yarn: true
  directories:
    - node_modules
# script:
  # - yarn workspace @mcansh/blog-www test
before_install:
  - export PATH="$(yarn global bin):$PATH"
  - yarn global add greenkeeper-lockfile@1
before_script:
  - yarn install --production=false
  - greenkeeper-lockfile-update
after_script:
  - greenkeeper-lockfile-upload
notifications:
  email:
    on_success: never
    on_failure: always
